### ISSUE TITLE
CI/CD error - show scraper failing

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#550]
Looks like our show scraper is failing regularly, which means no new episodes (i.e. LUP-0523) are being added to hugo. 

Anyone have time/expertise to have a gander?

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/actions/runs/5873193949/job/15926085010#step:6:120

```
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/show-scraper-cgG_fbj7/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/jupiterbroadcasting.com/jupiterbroadcasting.com/show-scraper/./scraper.py", line 862, in <module>
    main()
  File "/home/runner/work/jupiterbroadcasting.com/jupiterbroadcasting.com/show-scraper/./scraper.py", line 849, in main
    scrape_episodes_from_fireside(validated_config.shows, executor)
  File "/home/runner/work/jupiterbroadcasting.com/jupiterbroadcasting.com/show-scraper/./scraper.py", line 802, in scrape_episodes_from_fireside
    .json()
  File "/home/runner/.local/share/virtualenvs/show-scraper-cgG_fbj7/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
```

**Comment by gerbrent** [comment]
might be more appropriate to move this Issue to https://github.com/JupiterBroadcasting/show-scraper

**Comment by noblepayne** [comment]
I suspect the scraper started failing because the Office Hours feed is now redirected to the new podcasting 2.0 test feed. Unfortunately, this redirects both the `/rss ` and the `/json` routes. Thus, when the scraper tries to grab info from the `/json` route, it actually ends up with the feed XML.

```sh
# redirected office feed
$ curl -vLo/dev/null http://officehours.hair/json 2>&1 | grep -i location:
< Location: https://www.officehours.hair/json
< location: https://feeds.us-east-1.linodeobjects.com/office/office.xml

# compare to a non-redirected feed
$ curl -vLo/dev/null http://linuxunplugged.com/json 2>&1 | grep -i location:
< Location: https://linuxunplugged.com/json
```

A fix for the redirect will likely need to be a JB backend solution, but the scraper could have more error handling (and logging) when processing individual shows and episodes, While we might still want it to fail out entirely if it encounters a problem (at least without finer-grained error reporting), it would be nice to know where/why it failed. We could also consider other failure modes that might include a best-effort scrape.

This time the script is failing [here](https://github.com/JupiterBroadcasting/show-scraper/blob/main/scraper.py#L800-L803).
